export default {
    primary: '#FF4B3A',
    secondary: '#FFC700',
    background: '#FFFFFF',
    text: '#222222',
    lightText: '#757575',
    border: '#EEEEEE',
    success: '#4CAF50',
    error: '#F44336',
    warning: '#FFC107',
    info: '#2196F3',
    card: '#FFFFFF',
    placeholder: '#BBBBBB',
    badge: '#FF4B3A',
    discount: '#FF4B3A',
    freeship: '#00BFA5',
    preferred: '#FF4B3A',
    sellingFast: '#FF4B3A',
    tabBar: '#FFFFFF',
    tabBarInactive: '#AAAAAA',
    tabBarActive: '#FF4B3A',
  };